### ISSUE TITLE
REQUEST for SURROUND CONTROL

### ISSUE THREAD

**Issue by shouweiteoh** [bitfocus/companion-module-yamaha-scp#17]
Hi, 

Would be great if I could request to use Surround control as well.

Tried to capture using macro but no luck as well.. 

Any idea if this is possible ? Would love to setup a button to change divergence on selected channel.

Thanks !!

<img width="453" alt="Screenshot 2020-07-24 at 6 21 12 PM" src="https://user-images.githubusercontent.com/67238979/88398374-e45ae600-cdf7-11ea-9415-93f8efb3e532.png">

**Comment by MeestorX** [comment]
Thinking that the surround settings might not be needed, I disabled them to reduce the # of commands in the action dropdown. (There's many commands and some of them didn't seem useful).
If you look at the file [CL5 Parameters-1.txt](https://github.com/bitfocus/companion-module-yamaha-scp/blob/master/CL5%20SCP%20Parameters-1.txt) you can see the command list. Any commands listed with OK in front of them are active, and ones listed with "--" are inactive.
Adding all the commands with "Div" is easy enough, but do you think there are other surround commands that should be enabled as well?
As you noticed, the debug menu will show you the names of commands as they come in from the mixer.

**Comment by shouweiteoh** [comment]
I personally feel that "div" will be a helpful one as Yamaha does not enable them in "USER DEFINED KEYS" and will be helpful as now I'll have to create scene just to toggle between 70 / 30 divergence for the vocal microphone. It will certainly be a great tools to be able to trigger it from streamdeck.

How can I add the DIV command or how can i make them work? Thanks for the quick respond !

**Comment by MeestorX** [comment]
Ok, no others then at this time?
You can't enable them, as the file becomes part of companion when they build. That's why if I'm going to make them do another build, I would add whatever commands are needed, as well as the div command.

BTW, if you find that the SCP commands are too limiting, and you're using a CL or QL console, I have another module that has additional functionality, but it's still a "work in progress".
It's available at [checkcheckonetwo.com](https://www.checkcheckonetwo.com/forum/showthread.php?1718-Custom-Companion-Build-for-Yamaha-and-A-amp-H).
[Here's a demo](https://youtu.be/8nKuF3Dq3I8).

**Comment by shouweiteoh** [comment]
Hi,

BTW I would to thank you for developing this, its awesome !! 
Understood. Would it be possible for you to enable all of them, but maybe not having them in the dropdown menu but rather have one empty column for us to paste whatever command we might need so it wont cloud the action dropdown? Would it work better ?

I've been trying to register myself in your forum but upon clicking "complete registration" i am always directed to http://www.klikhierniet.net/ another spam website. Have not successfully register myself to download.

ANyway thank you again !!

**Comment by MeestorX** [comment]
Sorry about that, the system must be mistaking your Ip or email as a spammer. Click the “Contact Us” button at the bottom of any page and I’ll register you manually.

Ill see what I can do about the commands. Thank you for your kind words!

**Comment by shouweiteoh** [comment]
Hi Andy,

Managed to register myself on the forum. Should I post my question here or there?

I've ran into one problem where i am trying to change the input of certain channel it just doesnt reflect on the console. I have tried both manually selecting the command and also recording macro. both doesnt work.

sending you the screenshot of the debug for your reference, this is just one button pressed. weird that it is sending patch to DANTE39 but returned set to OMNI 1, what did I do wrong?

![Screenshot 2020-07-26 at 3 11 07 PM](https://user-images.githubusercontent.com/67238979/88473700-c35ad800-cf52-11ea-824b-7376cb5c3b8e.png)

**Comment by MeestorX** [comment]
The forum would be preferred, but let me say what I notice from the log:
See that your Mixer replies with `OKm` instead of the usual `OK` in some cases, which means in SCP speak: Ok, "but not quite"...
So, the command executed, but not exactly the way it was commanded.
For example, if you try to set something past it's range like
` set MIXER:Current/InCh/Port/HA Gain 64 0 1100` Which means set the gain to +11db, past what the console can set, it would reply:
`OKm set MIXER/Current/InCh/Port/HA Gain 64 0 1000` Meaning that the gain was set, but not to the exact value you asked.

So, I might conclude that channel 64 and 65 are being asked set to Dante39 and 40, but in reality, Dante39 and 40 are already connected to Omni1 and Omni2 maybe?

Let's continue the discussion on the forum as it would be interesting to know what specifically is happening in your case.

Please close this case when you get a chance, as the original issue has been remedied. I've asked that the div commands be added to the commands, so probably the next Companion build will have them.
